### PR TITLE
[CLEANUP] Stop using `$_EXTKEY`

### PR DESCRIPTION
**Pull request by oliverklee**
It is not recommended to use this variable anymore.

### CODE REVIEW

**Comment by simonschaufi** [comment]
@oliverklee source of information?

**Comment by oliverklee** [comment]
@simonschaufi https://github.com/TYPO3/typo3/commit/71b8504d1d81adb40689d79396d7be958f5f1dbc

**Comment by simonschaufi** [comment]
This is only true for ext_localconf and ext_tables but not for ext_emconf: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/DeclarationFile/Index.html

See the note there! Maybe this is outdated but officially it's still true ;)

**Comment by oliverklee** [comment]
Oh, good to know. Thanks for the pointer, @simonschaufi!

Closing.

**Pull request closed without merging**
